CREATE DEFINER=`root`@`localhost` FUNCTION `get_fiscal_quater`(
calender_date DATE
) RETURNS char(2) CHARSET latin1
    DETERMINISTIC
BEGIN
DECLARE M TINYINT;
DECLARE QTR CHAR(2);
SET M = MONTH(CALENDER_DATE);
CASE
WHEN M=(9,10,11) THEN
SET QTR = "Q1";
WHEN M=(12,1,2) THEN 
SET QTR ="Q2";
WHEN M=(3,4,5) THEN
SET QTR ="Q3";
ELSE 
SET QTR="Q4";

END CASE ;
RETURN QTR;
END